de:
  intro_lead: Was wir machen
  intro_text: Wir identifizieren die Bedürfnisse unserer Kunden, gestalten relevante Prozesse, konzipieren und optimieren digitale Produkte und Services, implementieren Software und befähigen unsere Kunden nachhaltig in diesen Aktivitäten.
  intro_services_title: Unsere Kompetenzfelder

  slides:
    - name: User Research
      img: dlabs_approach-research.jpg
      text: Wir erfassen die Bedürfnisse und Anforderungen, wir testen die Usability und User Experience. Wir sind der erfahrene Partner für unsere Kunden und begleiten die Konzeption und Entwicklung. Im Anschluss validieren wir die Prototypen und Produkte.
      color: yellow
    - name: Digital Experience Design
      img: dlabs_approach-design.jpg
      text: Wir sind Gestalter der Erfahrbarkeit von digitalen Produkten und Services. Im agilen Design-Prozess erarbeiten wir digitale Produkte und Services, die Menschen wirklich brauchen und optimal benutzen können. Wir arbeiten mit UX Researchern, Beratern und Software-Entwicklern Hand in Hand. Dabei beziehen wir den Kunden eng mit ein und validieren Lösungsansätze mit potenziellen Nutzern.
      color: darkBlue
    - name: Software Engineering
      img: dlabs_approach-engineering.jpg
      text: Wir sind Experten auf den Gebieten der Planung, Analyse, Konzeption und Implementierung von Anwendungssoftware und Webapplikationen für Desktop und Mobile.
      color: red
    - name: Enabling & Coaching
      img: about.jpg
      text: Wir entwickeln anhand der Bedürfnisse unserer Teilnehmer maßgeschneiderte Formate. In diesen nutzerzentrierten Workshops und Trainings vermitteln wir die erforderlichen Fähigkeiten, welche insbesondere im Kontext von Innovationsprozessen und agilen Arbeitsweisen benötigt werden. 
      color: green
    - name: Business & Innovation
      img: about.jpg
      text: Als Spezialisten entwickeln wir gemeinsam mit unseren Kunden digitale Lösungen. Unsere langjährige Erfahrung und unsere persönliche Leidenschaft sind der perfekte Mix, gemeinsam die besten digitalen Services zu kreieren. Wir entwickeln Strategien und unterstützen unsere Kunden bei der strategischen Neuausrichtung. 
      color: purple

  list_link_text: Zu unseren Leistungen und Methoden
  services_title: Leistungen und Methoden
  services_all_button: Alle
  back_button_text: Zurück zur Übersicht
  search_placeholder: Suche nach...
  filter_button_label: Filter

en:
  intro_lead: What We Do
  intro_text: We identify the needs of our customers, design relevant processes, conceive and optimize digital products and services, implement software and sustainably enable our customers in these activities.
  intro_services_title: Our Fields of Expertise

  slides:
    - name: User Research
      img: dlabs_approach-research.jpg
      text: We learn the needs and requirements; we test the usability and user experience. We are the experienced partner for our customers and accompany the conception and development. We then validate the prototypes and products.
      color: yellow
    - name: Digital Experience Design
      img: dlabs_approach-design.jpg
      text: Wir erfassen die Bedürfnisse und Anforderungen, wir testen die Usability und User Experience. Wir sind der erfahrene Partner für unsere Kunden und begleiten die Konzeption und Entwicklung. Im Anschluss validieren wir die Prototypen und Produkte.
      color: darkBlue
    - name: Software Engineering
      img: dlabs_approach-engineering.jpg
      text: Wir sind Experten auf den Gebieten der Planung, Analyse, Konzeption und Implementierung von Anwendungssoftware und Webapplikationen für Desktop und Mobile.
      color: red
    - name: Enabling & Coaching
      img: about.jpg
      text: Als Spezialisten entwickeln wir gemeinsam mit unseren Kunden digitale Lösungen. Unsere langjährige Erfahrung und unsere persönliche Leidenschaft sind der perfekte Mix, gemeinsam die besten digitalen Services zu kreieren. Wir entwickeln Strategien und unterstützen unsere Kunden bei der strategischen Neuausrichtung. Als kompetenter Begleiter fungieren wir bei Innovations- und Changeprozessen und helfen bei der Produkt- und Serviceoptimierung.
      color: green
    - name: Business & Innovation
      img: about.jpg
      text: Als Spezialisten entwickeln wir gemeinsam mit unseren Kunden digitale Lösungen. Unsere langjährige Erfahrung und unsere persönliche Leidenschaft sind der perfekte Mix, gemeinsam die besten digitalen Services zu kreieren. Wir entwickeln Strategien und unterstützen unsere Kunden bei der strategischen Neuausrichtung. Als kompetenter Begleiter fungieren wir bei Innovations- und Changeprozessen und helfen bei der Produkt- und Serviceoptimierung.
      color: purple

  list_link_text: Zu unseren Leistungen und Methoden
  services_title: Leistungen und Methoden
  services_all_button: Alle
  back_button_text: Zurück zur Übersicht
  filter_button_label: Filter
